---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: teslamate-secret
    template:
      data:
        DATABASE_USER: teslamate
        DATABASE_PASS: "{{ .db_password }}"
        DATABASE_NAME: teslamate
        DATABASE_HOST: teslamate-postgresql
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        MQTT_HOST: mosquitto.home.svc.cluster.local
        MQTT_USERNAME: "{{ .mqtt_username }}"
        MQTT_PASSWORD: "{{ .mqtt_password }}"
        POSTGRES_PASSWORD: "{{ .db_password }}"
  dataFrom:
    - extract:
        key: teslamate
