---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: unpackerr-secret
    template:
      data:
        UN_SONARR_0_URL: "http://sonarr.media.svc.cluster.local:8989"
        UN_SONARR_0_API_KEY: "{{ .sonarr_api_key }}"
        UN_RADARR_0_URL: "http://radarr.media.svc.cluster.local:7878"
        UN_RADARR_0_API_KEY: "{{ .radarr_api_key }}"
        UN_RADARR_1_URL: "http://radarr-4k.media.svc.cluster.local:7878"
        UN_RADARR_1_API_KEY: "{{ .radarr_4k_api_key }}"
  dataFrom:
    - extract:
        key: unpackerr
