---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: openwebui-secret
    template:
      data:
        OAUTH_CLIENT_ID: "{{ .oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: openwebui
