---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: samba-secret
    template:
      data:
        SAMBA_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: samba
