---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: samba
spec:
  chartRef:
    kind: OCIRepository
    name: samba
  interval: 1h
  values:
    controllers:
      samba:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/crazy-max/samba
              tag: 4.21.3
            env:
              TZ: America/New_York
              SAMBA_WORKGROUP: WORKGROUP
            envFrom:
              - secretRef:
                  name: samba-secret
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0

    service:
      app:
        controller: samba
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.0.3.55"
        ports:
          smb:
            port: 445

    persistence:
      ha-config:
        existingClaim: config-home-assistant-0
        globalMounts:
          - path: /share/home-assistant
      config:
        type: configMap
        identifier: config
        globalMounts:
          - path: /data/config.yml
            subPath: config.yml

    configMaps:
      config:
        data:
          config.yml: |
            auth:
              - user: homeassistant
                group: homeassistant
                uid: 0
                gid: 0
                password_file: /run/secrets/samba_password
            share:
              - name: home-assistant
                path: /share/home-assistant
                browsable: yes
                readonly: no
                guestok: no
                validusers: homeassistant
