---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tautulli
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: tautulli-secret
    template:
      data:
        TAUTULLI_API_KEY: "{{ .api_key }}"
        PLEX_TOKEN: "{{ .plex_token }}"
  dataFrom:
    - extract:
        key: tautulli
