---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: booklore-secret
    template:
      data:
        SPRING_DATASOURCE_PASSWORD: "{{ .db_password }}"
        MYSQL_ROOT_PASSWORD: "{{ .db_password }}"
        MYSQL_PASSWORD: "{{ .db_password }}"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: booklore
