apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: homarr-secret
    template:
      data:
        db-encryption-key: "{{ .db_encryption_key }}"
        oidc-client-id: "{{ .oidc_client_id }}"
        oidc-client-secret: "{{ .oidc_client_secret}}"
        # SECRET_ENCRYPTION_KEY: "{{ .SECRET_ENCRYPTION_KEY }}"
        # OIDC_ISSUER: "{{ .OIDC_ISSUER }}"
        # OIDC_NAME: "{{ .OIDC_NAME }}"
        # OIDC_SCOPE: "{{ .OIDC_SCOPE }}"
        # NEXTAUTH_URL: "{{ .NEXTAUTH_URL }}"
        # NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
  dataFrom:
    - extract:
        key: homarr
