apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: homarr-secret
    template:
      data:
        # HOMARR_PASSWORD: "{{ .HOMARR_PASSWORD }}"
        db-encryption-key: "{{ .db_encryption_key }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET}}"
        OIDC_ISSUER: "{{ .OIDC_ISSUER }}"
        OIDC_NAME: "{{ .OIDC_NAME }}"
        OIDC_SCOPE: "{{ .OIDC_SCOPE }}"
        NEXTAUTH_URL: "{{ .NEXTAUTH_URL }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
  dataFrom:
    - extract:
        key: homarr
