---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: homarr
  interval: 1h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.43.1"
    rbac:
      enabled: true
    env:
      AUTH_PROVIDERS: "credentials,oidc"
      TZ: "America/New_York"
      # LOG_LEVEL: "debug"
    envSecrets:
      dbEncryption:
        existingSecret: "homarr-secret"
        key: "db-encryption-key"
      OIDC_CLIENT_ID:
        existingSecret: homarr-secret
        key: OIDC_CLIENT_ID
      OIDC_CLIENT_SECRET:
        existingSecret: homarr-secret
        key: OIDC_CLIENT_SECRET
      OIDC_ISSUER:
        existingSecret: homarr-secret
        key: OIDC_ISSUER
      OIDC_NAME:
        existingSecret: homarr-secret
        key: OIDC_NAME
      OIDC_SCOPE:
        existingSecret: homarr-secret
        key: OIDC_SCOPE
      NEXTAUTH_URL:
        existingSecret: homarr-secret
        key: NEXTAUTH_URL
      NEXTAUTH_SECRET:
        existingSecret: homarr-secret
        key: NEXTAUTH_SECRET

    #   HOMARR_PASSWORD:
    #     existingSecret: {{ .Release.Name}}-secret
    #     key: HOMARR_PASSWORD
    httproute:
      enabled: true
      hostnames:
        - homarr.${SECRET_DOMAIN}
        - home.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
      rules:
        - backendRefs:
            - name: homarr
              port: 7575
    persistence:
      homarrDatabase:
        enabled: true
        size: 1Gi
        storageClassName: "longhorn" # Use default (Longhorn)
