---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: homarr
  interval: 1h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.43.1"
    rbac:
      enabled: true
    env:
      AUTH_PROVIDERS: "credentials"
      # AUTH_OIDC_AUTO_LOGIN: true #To sign in with Authentik automatically
      # AUTH_OIDC_CLIENT_NAME: "authentik"
      # AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
      # BASE_URL: "https://home.${SECRET_DOMAIN}"
      # NEXTAUTH_URL: "https://home.${SECRET_DOMAIN}"
      # AUTH_OIDC_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/homarr"
      # AUTH_OIDC_URI: "https://auth.${SECRET_DOMAIN}/application/o/authorize"
      # AUTH_LOGOUT_REDIRECT_URL: "https://${AUTH_DOMAIN}/application/o/homarr/end-session/"
      TZ:
        "America/New_York"
        # LOG_LEVEL: "debug"
    # envFrom:
    #   secretRefs:
    #     - name: "homarr-secret"
    #         AUTH_OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
    # AUTH_OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
    envSecrets:
      dbEncryption:
        existingSecret: "homarr-secret"
        key: "db-encryption-key"
    #   HOMARR_PASSWORD:
    #     existingSecret: {{ .Release.Name}}-secret
    #     key: HOMARR_PASSWORD
    httproute:
      enabled: true
      hostnames:
        - homarr.${SECRET_DOMAIN}
        - home.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
      rules:
        - backendRefs:
            - name: homarr
              port: 7575
    persistence:
      homarrDatabase:
        enabled: true
        size: 1Gi
        storageClassName: "longhorn" # Use default (Longhorn)
