---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: homarr
  interval: 1h
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.50.0"
    podAnnotations:
      reloader.stakater.com/auto: "true"
    rbac:
      enabled: true
    env:
      TZ: "America/New_York"
      # LOG_LEVEL: "debug"
      AUTH_PROVIDERS: "oidc,credentials"
      AUTH_LOGOUT_REDIRECT_URL: "https://auth.${SECRET_DOMAIN}/application/o/homarr/end-session/"
      AUTH_SESSION_EXPIRY_TIME: "14d"
      AUTH_OIDC_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/homarr"
      AUTH_OIDC_CLIENT_NAME: "authentik"
      AUTH_OIDC_AUTO_LOGIN: true #To sign in with Authentik automatically
      AUTH_OIDC_GROUPS_ATTRIBUTE: "groups"
      # BASE_URL: "https://home.${SECRET_DOMAIN}"
      # NEXTAUTH_URL: "https://home.${SECRET_DOMAIN}"
      # AUTH_OIDC_URI: "https://auth.${SECRET_DOMAIN}/application/o/authorize"
    envSecrets:
      dbEncryption:
        existingSecret: "homarr-secret"
        key: "db-encryption-key"
      authOidcCredentials:
        existingSecret: "homarr-secret"
        oidcClientId: "oidc-client-id"
        oidcClientSecret: "oidc-client-secret"
    httproute:
      enabled: true
      hostnames:
        - homarr.${SECRET_DOMAIN}
        - home.${SECRET_DOMAIN}
      parentRefs:
        - name: envoy-internal
          namespace: network
          sectionName: https
      rules:
        - backendRefs:
            - name: homarr
              port: 7575
    persistence:
      homarrDatabase:
        enabled: true
        size: 1Gi
        storageClassName: "longhorn" # Use default (Longhorn)
