---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ttyd
spec:
  chartRef:
    kind: OCIRepository
    name: ttyd
  interval: 1h
  values:
    controllers:
      ttyd:
        containers:
          app:
            image:
              repository: ghcr.io/tsl0922/ttyd
              tag: 1.7.7
            args:
              - -W
              - sh
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534

    service:
      app:
        controller: ttyd
        ports:
          http:
            port: 7681

    route:
      app:
        hostnames: ["hass-terminal.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 7681
