---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoscan
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: autoscan-secret
    template:
      data:
        PLEX_TOKEN: "{{ .plex_token }}"
  dataFrom:
    - extract:
        key: autoscan
