---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifiarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: notifiarr-secret
    template:
      data:
        DN_API_KEY: "{{ .api_key }}"
        DN_SONARR_0_URL: "http://sonarr.media.svc.cluster.local:8989"
        DN_SONARR_0_API_KEY: "{{ .sonarr_api_key }}"
        DN_RADARR_0_URL: "http://radarr.media.svc.cluster.local:7878"
        DN_RADARR_0_API_KEY: "{{ .radarr_api_key }}"
        DN_RADARR_1_URL: "http://radarr-4k.media.svc.cluster.local:7878"
        DN_RADARR_1_API_KEY: "{{ .radarr_4k_api_key }}"
        DN_PROWLARR_0_URL: "http://prowlarr.media.svc.cluster.local:9696"
        DN_PROWLARR_0_API_KEY: "{{ .prowlarr_api_key }}"
        DN_PLEX_URL: "http://plex.media.svc.cluster.local:32400"
        DN_PLEX_TOKEN: "{{ .plex_token }}"
  dataFrom:
    - extract:
        key: notifiarr
