---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: sqlite
      path: /data/data.db

    security:
      oidc:
        issuer-url: https://auth.thegeekybits.com/application/o/gatus/
        redirect-url: https://gatus.thegeekybits.com/authorization-code/callback
        client-id: "${OIDC_CLIENT_ID}"
        client-secret: "${OIDC_CLIENT_SECRET}"
        scopes: ["openid", "email", "profile"]

    ui:
      title: Status | Home Ops
      header: Status

    endpoints:
      - name: Gateway (Internal)
        group: infrastructure
        url: "https://echo.${SECRET_DOMAIN}"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 2000"

      - name: Cloudflare
        group: external
        url: "https://1.1.1.1/cdn-cgi/trace"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 1000"

      - name: Google
        group: external
        url: "https://www.google.com"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 1000"
