---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: opencode-secret
    template:
      data:
        OPENCODE_SERVER_PASSWORD: "{{ .server_password }}"
        OPENCODE_SERVER_USERNAME: "{{ .server_username }}"
        ANTHROPIC_API_KEY: "{{ .anthropic_api_key }}"
        OPENAI_API_KEY: "{{ .openai_api_key }}"
  dataFrom:
    - extract:
        key: opencode
