---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shlink
spec:
  chartRef:
    kind: OCIRepository
    name: shlink
  interval: 1h
  values:
    controllers:
      shlink:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17"
            env:
              INIT_POSTGRES_HOST: shlink-postgresql
              INIT_POSTGRES_SUPER_USER: postgres
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: POSTGRES_PASSWORD
              INIT_POSTGRES_USER: shlink
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: POSTGRES_PASSWORD
              INIT_POSTGRES_DBNAME: shlink
        containers:
          app:
            image:
              repository: shlinkio/shlink
              tag: 4.4.1
            env:
              TZ: America/New_York
              DEFAULT_DOMAIN: "s.${SECRET_DOMAIN}"
              IS_HTTPS_ENABLED: "true"
              DB_DRIVER: postgres
              DB_HOST: shlink-postgresql
              DB_PORT: "5432"
              DB_NAME: shlink
              DB_USER: shlink
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: DB_PASSWORD
              INITIAL_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: INITIAL_API_KEY
              GEOLITE_LICENSE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: GEOLITE_LICENSE_KEY
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/health
                    port: &port 8080
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 128Mi
      web:
        containers:
          app:
            image:
              repository: shlinkio/shlink-web-client
              tag: 4.3.1
            probes:
              liveness: &webprobes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &webport 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *webprobes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
      postgresql:
        type: Deployment
        containers:
          postgres:
            image:
              repository: postgres
              tag: "17-alpine"
            env:
              POSTGRES_USER: postgres
              POSTGRES_DB: shlink
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: shlink-secret
                    key: POSTGRES_PASSWORD
              PGDATA: /var/lib/postgresql/data/pgdata
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 256Mi
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
    service:
      app:
        controller: shlink
        ports:
          http:
            port: *port
      web:
        controller: web
        ports:
          http:
            port: *webport
      postgresql:
        controller: postgresql
        ports:
          postgres:
            port: 5432
    persistence:
      db-data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
        advancedMounts:
          postgresql:
            postgres:
              - path: /var/lib/postgresql/data
    route:
      app:
        hostnames: ["s.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
      web:
        hostnames: ["shlink.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: web
                port: *webport
